export enum RoutesName {
    Splash = 'SplashScreen',
    Login = 'LoginScreen',
    Register = 'RegisterScreen',
    BottomTab = 'BottomTab',
    Following = 'FollowingScreen',
    Home = 'HomeScreen',
    Profile = 'ProfileScreen',
    Redeem = 'RedeemScreen',
    UserProfile = 'UserProfileScreen',
    FeedReelScroll = 'FeedReelScrollScreen',
    PickReel = 'PickReelScreen',
    ReelScroll = 'ReelScrollScreen',
    UploadReel = 'UploadReelScreen',
  }